---
- name: Atualiza sistema
  apt:
    update_cache: yes
    upgrade: yes

- name: Instalar chrony (NTP)
  apt:
    name: chrony
    state: present

- name: Configurar timezone
  timezone:
    name: America/Recife

- name: Criar grupo ifpb
  group:
    name: ifpb

- name: Criar usuário sergio1
  user:
    name: sergio1
    groups: ifpb
    shell: /bin/bash

- name: Instalar cliente NFS
  apt:
    name: nfs-common
    state: present

- name: Permitir sudo para grupo ifpb
  copy:
    dest: /etc/sudoers.d/ifpb
    content: "%ifpb ALL=(ALL) NOPASSWD:ALL"
    mode: '0440'

- name: Configurar mensagem de boas-vindas SSH
  copy:
    dest: /etc/motd
    content: "Acesso monitorado e restrito aos usuários autorizados!!!"

- name: Configurar SSH seguro
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^X11Forwarding', line: 'X11Forwarding yes' }

- name: Criar grupo de acesso SSH
  group:
    name: vagrantifpb

- name: Adicionar sergio1 ao grupo SSH
  user:
    name: sergio1
    groups: vagrantifpb
    append: yes

- name: Cria usuário sergio1
  user:
    name: sergio1
    shell: /bin/bash
    groups: sudo
    state: present

- name: Gera chave SSH se ainda não existir
  delegate_to: localhost
  become: false
  shell: |
    mkdir -p ansible/chaves_publicas
    if [ ! -f ansible/chaves_publicas/sergio1 ]; then
      ssh-keygen -t rsa -b 2048 -f ansible/chaves_publicas/sergio1 -N ""
    fi
  run_once: true

- name: Instala chave pública no usuário sergio1
  authorized_key:
    user: sergio1
    key: "{{ lookup('file', 'ansible/chaves_publicas/sergio1.pub') }}"
