---
- name: Atualiza sistema
  apt:
    update_cache: yes
    upgrade: yes

- name: Cria usuário sergio1
  user:
    name: sergio1
    shell: /bin/bash
    groups: sudo
    state: present

- name: Gera chave SSH se ainda não existir
  delegate_to: localhost
  become: false
  shell: |
    mkdir -p ansible/chaves_publicas
    if [ ! -f ansible/chaves_publicas/sergio1 ]; then
      ssh-keygen -t rsa -b 2048 -f ansible/chaves_publicas/sergio1 -N ""
    fi
  run_once: true

- name: Instala chave pública no usuário sergio1
  authorized_key:
    user: sergio1
    key: "{{ lookup('file', 'ansible/chaves_publicas/sergio1.pub') }}"
