---
- name: Atualizando pacotes
  apt:
    update_cache: yes
    upgrade: dist

- name: Instalar chrony (NTP)
  apt:
    name: chrony
    state: present

- name: Configurar timezone
  timezone:
    name: America/Recife

- name: Criar grupo ifpb
  group:
    name: ifpb

- name: Criar usuário sergio1
  user:
    name: sergio1
    groups: ifpb
    shell: /bin/bash

- name: Instalar cliente NFS
  apt:
    name: nfs-common
    state: present

- name: Permitir sudo para grupo ifpb
  copy:
    dest: /etc/sudoers.d/ifpb
    content: "%ifpb ALL=(ALL) NOPASSWD:ALL"
    mode: '0440'

- name: Configurar mensagem de boas-vindas SSH
  copy:
    dest: /etc/motd
    content: "Acesso monitorado e restrito aos usuários autorizados!!!"

- name: Configurar SSH seguro
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^X11Forwarding', line: 'X11Forwarding yes' }

- name: Criar grupo de acesso SSH
  group:
    name: vagranteifpb

- name: Adicionar sergio1 ao grupo SSH
  user:
    name: sergio1
    groups: vagranteifpb
    append: yes

- name: Criar chave pública para sergio1
  authorized_key:
    user: sergio1
    key: "{{ lookup('file', 'chaves_publicas/sergio1.pub') }}"
